version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network1
  api:
    build: .
    ports: 
      - "8080:8080"
    links:
      - "mongodb:mongodb"
      - "rabbitmq:rabbitmq"
    depends_on:
      - "rabbitmq"
      - "mongodb"
    networks:
      - network1
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - network1
      
volumes:
   mongodata:

networks:
   network1: