version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network1
  api:
    build: .
    ports: 
      - "8080:8080"
    links:
      - "mongodb:mongodb"
    networks:
      - network1
      
volumes:
   mongodata:

networks:
   network1: